### ISSUE TITLE
Unite buffer freezes if called after expanding a (Ultisnips) snippet

### ISSUE THREAD

**Issue by petobens** [Shougo/neomru.vim#27] opened 2015-09-29 20:53 UTC
Consider the following minimal vimrc:

```vim
set nocompatible

let $ONEDRIVE_HOME = expand('C:/OD/Users/Pedro')
let $DOTVIM = expand('$ONEDRIVE_HOME/vimfiles')
let $CACHE = expand('$DOTVIM/cache')

set runtimepath+=$DOTVIM/bundle/ultisnips/
set runtimepath+=$DOTVIM/bundle/neomru/
set runtimepath+=$DOTVIM/bundle/unite/

filetype plugin indent on

let g:UltiSnipsSnippetDirectories = [$DOTVIM . '\testsnippet']

call unite#custom#profile('default', 'context', { 'start_insert' : 1 })
let g:neomru#file_mru_path = $CACHE . '/plugins/unite/mru/file'
```
where the `$DOTVIM\testsnippet` directory contains only the file  `python.snippets`:
```
snippet inp "Import numpy" b
${1:import numpy as np}$0
endsnippet
```

Now, as in the GIF, do the following:

i) Open Gvim and run `:e C:\Users\Pedro\Desktop\foo.py`
ii) Get into insert mode and type `inp` + `<TAB>` (to expand the snippet)
iii) Once the snippet expands press `<BACKSPACE>` to delete the visual text.
iv) Press `<ESC>` to exit insert mode and then run `:Unite neomru/file`
v) When the Unite buffer opens press `<DOWN>` (down arrow key) three times

You will see that Gvim freezes after pressing `<DOWN>` the second time (i.e I cannot reach the third candidate).

![blahhh](https://cloud.githubusercontent.com/assets/2583971/10177801/923baa26-66d2-11e5-892e-b1b41f47b581.gif)

**Comment by Shougo** [comment] 2015-10-01 21:17
Really?
It is neomru.vim problem?  I will test it though...

**Comment by petobens** [comment] 2015-10-01 22:03
It might be a Ultisnips problem but I tried it with different Unite sources and the only one that seems to generate the problem is neomru.

**Comment by Shougo** [comment] 2015-10-03 00:30
Reproduced.  But it is not neomru/unite bug.
If I disable `UltiSnips#CursorMoved()` function, it works.
It is UltiSnips bug.  Closing.

**Closed by Shougo** 2015-10-03 00:30 UTC

**Comment by petobens** [comment] 2015-10-03 04:28
Thanks @Shougo for looking into this. I reported the Issue in the Ultisnips repository.

**Comment by SirVer** [comment] 2015-10-04 12:28
Related UltiSnips bug: https://github.com/SirVer/ultisnips/issues/578. I think it is a bad interaction between plugins, not a bug in either.
